using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace Sample.Api.Controllers.V1
{
    using System;

    /// <summary>
    ///
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.ControllerBase" />
    /// <autogeneratedoc />
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    [ApiVersion("1.0", Deprecated = true)]
    public class ValuesController : ControllerBase
    {
        /// <summary>
        /// Gets this instance.
        /// </summary>
        /// <returns></returns>
        /// <remarks>Here are some remarks</remarks>
        /// <autogeneratedoc />
        [HttpGet]
        [SwaggerOperation(Description="This is a kam test", OperationId = "kamtest")]
        public ActionResult<IEnumerable<string>> Get()
        {
            return new string[] { "value1-1.0", "value2-1.0" };
        }

        /// <summary>
        /// Puts the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="value">The value.</param>
        /// <autogeneratedoc />
        [HttpPut("{id}")]
        public void Put(int id, [FromBody][Required] string value = "kam")
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete1(int id)
        {
        }

        [HttpGet]
        [Route("Deprecated")]
        [Obsolete("This is replaced with a new method {something}")]
        public void DeprecatedMethod()
        {}
    }
}
